In [1]:
import time
from splinter import Browser
from bs4 import BeautifulSoup as bs
import pandas as pd

In [2]:
# Create path and setup local chrome browser
executable_path = {'executable_path': 'chromedriver'}
browser = Browser('chrome', **executable_path, headless=False)

In [3]:
# Alpine Team Page
url = 'https://usskiandsnowboard.org/alpine'
browser.visit(url)

In [4]:
# Pull HTML and Beautiful Soup
html = browser.html
soup = bs(html, 'html.parser')

In [5]:
# Alpine Name Loop
alpine_name = []
for items in soup.find_all(class_="views-field views-field-field-img-head-shot"):
    a_name = items.find_next_sibling().text
    alpine_name.append(a_name)

In [6]:
# Alpine Hometown Loop
alpine_hometown = []
for items in soup.find_all(class_="views-field views-field-title"):
    a_hometown = items.find_next_sibling().text
    alpine_hometown.append(a_hometown)

In [7]:
# Freeski Team Page
url = 'https://usskiandsnowboard.org/teams/freeski'
browser.visit(url)

In [8]:
# Pull HTML and Beautiful Soup
html = browser.html
soup = bs(html, 'html.parser')

In [9]:
# Freeski Name Loop
freeski_name = []
for items in soup.find_all(class_="views-field views-field-field-img-head-shot"):
    fski_name = items.find_next_sibling().text
    freeski_name.append(fski_name)

In [10]:
# Freeski Hometown Loop
freeski_hometown = []
for items in soup.find_all(class_="views-field views-field-title"):
    fski_hometown = items.find_next_sibling().text
    freeski_hometown.append(fski_hometown)

In [11]:
# Freestyle Team Page
url = 'https://usskiandsnowboard.org/teams/freestyle'
browser.visit(url)

In [12]:
# Pull HTML and Beautiful Soup
html = browser.html
soup = bs(html, 'html.parser')

In [13]:
# Freestyle Name Loop
freestyle_name = []
for items in soup.find_all(class_="views-field views-field-field-img-head-shot"):
    fstyle_name = items.find_next_sibling().text
    freestyle_name.append(fstyle_name)

In [14]:
# Freestyle Hometown
freestyle_hometown = []
for items in soup.find_all(class_="views-field views-field-title"):
    fstyle_hometown = items.find_next_sibling().text
    freestyle_hometown.append(fstyle_hometown)

In [15]:
# Cross Country Team Page
url = 'https://usskiandsnowboard.org/teams/cross-country'
browser.visit(url)

In [16]:
# Pull HTML and Beautiful Soup
html = browser.html
soup = bs(html, 'html.parser')

In [17]:
# Cross Country Name Loop
xc_name = []
for items in soup.find_all(class_="views-field views-field-field-img-head-shot"):
    cc_name = items.find_next_sibling().text
    xc_name.append(cc_name)

In [18]:
# Cross Country Hometown Loop
xc_hometown = []
for items in soup.find_all(class_="views-field views-field-title"):
    cc_hometown = items.find_next_sibling().text
    xc_hometown.append(cc_hometown)

In [19]:
# Ski Jumping Team Page
url = 'https://usskiandsnowboard.org/teams/ski-jumping'
browser.visit(url)

In [20]:
# Pull HTML and Beautiful Soup
html = browser.html
soup = bs(html, 'html.parser')

In [21]:
# Ski Jumping Name Loop
ski_jumping_name = []
for items in soup.find_all(class_="views-field views-field-field-img-head-shot"):
    sj_name = items.find_next_sibling().text
    ski_jumping_name.append(sj_name)

In [22]:
# Ski Jumping Hometown Loop
ski_jumping_hometown = []
for items in soup.find_all(class_="views-field views-field-title"):
    sj_hometown = items.find_next_sibling().text
    ski_jumping_hometown.append(sj_hometown)

In [23]:
# Nordic Combined Team Page
url = 'https://usskiandsnowboard.org/teams/nordic-combined'
browser.visit(url)

In [24]:
# Pull HTML and Beautiful Soup
html = browser.html
soup = bs(html, 'html.parser')

In [25]:
# Nordic Combined Name Loop
nordic_combined_name = []
for items in soup.find_all(class_="views-field views-field-field-img-head-shot"):
    nc_name = items.find_next_sibling().text
    nordic_combined_name.append(nc_name)

In [26]:
# Nordic Combined Hometown Loop
nordic_combined_hometown = []
for items in soup.find_all(class_="views-field views-field-title"):
    nc_hometown = items.find_next_sibling().text
    nordic_combined_hometown.append(nc_hometown)

In [27]:
# Snowboard Team Page
url = 'https://usskiandsnowboard.org/teams/snowboard'
browser.visit(url)

In [28]:
# Pull HTML and Beautiful Soup
html = browser.html
soup = bs(html, 'html.parser')

In [29]:
# Snowboard Name Loop
snowboard_name = []
for items in soup.find_all(class_="views-field views-field-field-img-head-shot"):
    snow_name = items.find_next_sibling().text
    snowboard_name.append(snow_name)

In [30]:
# Snowboard Hometown Loop
snowboard_hometown = []
for items in soup.find_all(class_="views-field views-field-title"):
    snow_hometown = items.find_next_sibling().text
    snowboard_hometown.append(snow_hometown)

In [31]:
# Create all lists into DataFrames
df1 = pd.DataFrame(alpine_name) 
df2 = pd.DataFrame(alpine_hometown)
df3 = pd.DataFrame(freeski_name)
df4 = pd.DataFrame(freeski_hometown)
df5 = pd.DataFrame(freestyle_name)
df6 = pd.DataFrame(freestyle_hometown)
df7 = pd.DataFrame(xc_name)
df8 = pd.DataFrame(xc_hometown)
df9 = pd.DataFrame(ski_jumping_name)
df10 = pd.DataFrame(ski_jumping_hometown)
df11 = pd.DataFrame(nordic_combined_name)
df12 = pd.DataFrame(nordic_combined_hometown)
df13 = pd.DataFrame(snowboard_name)
df14 = pd.DataFrame(snowboard_hometown)

In [32]:
# Rename each column depeding on whether it is a name or hometown
alpine_name_df = df1.rename(columns={ df1.columns[0]: "Name" })
alpine_hometown_df = df2.rename(columns={ df2.columns[0]: "Hometown" })
freeski_name_df = df3.rename(columns={ df3.columns[0]: "Name" })
freeski_hometown_df = df4.rename(columns={ df4.columns[0]: "Hometown" })
freestyle_name_df = df5.rename(columns={ df5.columns[0]: "Name" })
freestyle_hometown_df = df6.rename(columns={ df6.columns[0]: "Hometown" })
xc_name_df = df7.rename(columns={ df7.columns[0]: "Name" })
xc_hometown_df = df8.rename(columns={ df8.columns[0]: "Hometown" })
ski_jumping_name_df = df9.rename(columns={ df9.columns[0]: "Name" })
ski_jumping_hometown_df = df10.rename(columns={ df10.columns[0]: "Hometown" })
nordic_combined_name_df = df11.rename(columns={ df11.columns[0]: "Name" })
nordic_combined_hometown_df = df12.rename(columns={ df12.columns[0]: "Hometown" })
snowboard_name_df = df13.rename(columns={ df13.columns[0]: "Name" })
snowboard_hometown_df = df14.rename(columns={ df14.columns[0]: "Hometown" })

In [33]:
# Combine Name and Hometown for each team
alpine_df_noteam = pd.concat([alpine_name_df,alpine_hometown_df], axis=1)
freeski_df_noteam = pd.concat([freeski_name_df,freeski_hometown_df], axis=1)
freestyle_df_noteam = pd.concat([freestyle_name_df,freestyle_hometown_df], axis=1)
xc_df_noteam = pd.concat([xc_name_df,xc_hometown_df], axis=1)
ski_jumping_df_noteam = pd.concat([ski_jumping_name_df,ski_jumping_hometown_df], axis=1)
nordic_combined_df_noteam = pd.concat([nordic_combined_name_df,nordic_combined_hometown_df], axis=1)
snowboard_df_noteam = pd.concat([snowboard_name_df,snowboard_hometown_df], axis=1)

In [34]:
# Add team column to each team DF
alpine_df_noteam["Team"] = "Alpine"
freeski_df_noteam["Team"] = "Freeski"
freestyle_df_noteam["Team"] = "Freestyle"
xc_df_noteam["Team"] = "Cross Country"
ski_jumping_df_noteam["Team"] = "Ski Jumping"
nordic_combined_df_noteam["Team"] = "Nordic Combined"
snowboard_df_noteam["Team"] = "Snowboard"

In [35]:
# Update noteam df to final '(team)_df'
alpine_df = alpine_df_noteam
freeski_df = freeski_df_noteam
freestyle_df = freestyle_df_noteam
xc_df = xc_df_noteam
ski_jumping_df = ski_jumping_df_noteam
nordic_combined_df = nordic_combined_df_noteam
snowboard_df = snowboard_df_noteam

In [36]:
# Create final US Winter Olympic Team DF by merging all team DFs
us_winter_olympic_team = pd.concat([alpine_df, freeski_df, freestyle_df, xc_df, ski_jumping_df, nordic_combined_df, snowboard_df], axis=0)

In [37]:
# Reset the index
us_winter_olympic_team.reset_index()

     index               Name               Hometown       Team
0        0     Alice McKennis         Minturn, Colo.     Alpine
1        1     Breezy Johnson  Jackson Hole, Wyoming     Alpine
2        2      Bryce Bennett     Tahoe City, Calif.     Alpine
3        3  Jacqueline Wiles          Portland, Ore.     Alpine
4        4      Laurenne Ross             Bend, Ore.     Alpine
..     ...                ...                    ...        ...
188     40      Livia Molodyh          Hubbard, Ore.  Snowboard
189     41     Meghan Tierney           Eagle, Colo.  Snowboard
190     42      Mikey LaCroix      Shrewsbury, Mass.  Snowboard
191     43      Stacy Gaskill          Golden, Colo.  Snowboard
192     44    Aaron "AJ" Muss           Rumson, N.J.  Snowboard

[193 rows x 4 columns]

In [38]:
# Split Hometown into City and State

# Search for end of City by looking for the comma and space
new_us_winter_olympic_team = us_winter_olympic_team["Hometown"].str.split(", ", n = 1, expand = True) 
  
# Make Separate City column from new data frame 
us_winter_olympic_team["City"]= new_us_winter_olympic_team[0] 
  
# Make separate State column from new data frame 
us_winter_olympic_team["State"]= new_us_winter_olympic_team[1] 
  
# Drop Hometown column
us_winter_olympic_team.drop(columns =["Hometown"], inplace = True)

In [39]:
# Show US Winter Olympic Team
us_winter_olympic_team.head(50)

                   Name     Team              City                   State
0        Alice McKennis   Alpine           Minturn                   Colo.
1        Breezy Johnson   Alpine      Jackson Hole                 Wyoming
2         Bryce Bennett   Alpine        Tahoe City                  Calif.
3     Jacqueline Wiles    Alpine          Portland                    Ore.
4         Laurenne Ross   Alpine              Bend                    Ore.
5      Mikaela Shiffrin   Alpine           Edwards                   Colo.
6          Steven Nyman   Alpine           Jackson                    Wyo.
7            Ted Ligety   Alpine         Park City                    Utah
8            Tommy Ford   Alpine              Bend                    Ore.
9         Travis Ganong   Alpine        Tahoe City                  Calif.
10              AJ Hurt   Alpine     Carnelian Bay                  Calif.
11   Alice Merryweather   Alpine           Hingham                   Mass.
12          Ben Ritchie   Alpine        Waitsfield                     Vt.
13     Brian McLaughlin   Alpine        Waitsfield                     Vt.
14       Jared Goldberg   Alpine          Holladay                    Utah
15        Keely Cashman   Alpine        Strawberry                  Calif.
16         Kyle Negomir   Alpine         Littleton                   Colo.
17         Luke Winters   Alpine           Gresham                    Ore.
18         Nina O’Brien   Alpine            Denver                   Colo.
19        Paula Moltzan   Alpine        Burlington                 Vermont
20        River Radamus   Alpine           Edwards                   Colo.
21  Ryan Cochran-Siegle   Alpine        Starksboro                     Vt.
22            Sam Morse   Alpine         Sugarloaf                   Maine
23           Abi Jewett   Alpine            Ripton                     Vt.
24         Bridger Gile   Alpine             Aspen                   Colo.
25     Cooper Cornelius   Alpine  Glenwood Springs                   Colo.
26        Galena Wardle   Alpine             Aspen                   Colo.
27       George Steffey   Alpine       Springfield                    N.H.
28        Katie Hensien   Alpine         Park City                    Utah
29      Ainsley Proffit   Alpine         St. Louis                     Mo.
30       Alix Wilkinson   Alpine     Mammoth Lakes                  Calif.
31         Emma Resnick   Alpine              Vail                   Colo.
32        Isaiah Nelson   Alpine           Wayzata                    Minn
33           Jack Smith   Alpine        Sun Valley                   Idaho
34        Jacob Dilling   Alpine              Vail                   Colo.
35      Kellen Kinsella   Alpine           Edwards                   Colo.
36        Lauren Macuga   Alpine         Park City                    Utah
37       Zoe Zimmermann   Alpine           Gilford                     N.H
0          Aaron Blunck  Freeski     Crested Butte                   Colo.
1        Abigale Hansen  Freeski            Bishop                  Calif.
2         Alex Ferreira  Freeski             Aspen                   Colo.
3         Annalisa Drew  Freeski      Breckenridge  Colo. & Andover, Mass.
4           Birk Irving  Freeski       Winter Park                   Colo.
5       Brita Sigourney  Freeski         Park City                    Utah
6       Carly Margulies  Freeski     Mammoth Lakes                  Calif.
7            David Wise  Freeski              Reno                    Nev.
8           Devin Logan  Freeski         Park City                    Utah
9           Hunter Hess  Freeski              Bend                    Ore.
10        Lyman Currier  Freeski           Boulder                   Colo.
11        Taylor Seaton  Freeski              Avon                   Colo.

In [40]:
# Export to csv file
# us_winter_olympic_team.to_csv(r'data\us_winter_olympic_team.csv')